spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/corporate_travel
    username: admin
    password: admin123
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/corporate-travel

opa:
  url: http://opa:8181

logging:
  level:
    root: INFO
    com.corporate.travel: DEBUG