spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/corporate_travel
    username: admin
    password: admin123
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    locations: classpath:db/migration
    schemas: expense
    create-schemas: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/corporate-travel
          jwk-set-uri: http://keycloak:8080/realms/corporate-travel/protocol/openid-connect/certs

opa:
  url: http://opa:8181

logging:
  level:
    root: INFO
    com.corporate.travel: DEBUG