-- Create schemas for each service
CREATE SCHEMA IF NOT EXISTS keycloak;
CREATE SCHEMA IF NOT EXISTS travel;
CREATE SCHEMA IF NOT EXISTS expense;
CREATE SCHEMA IF NOT EXISTS approval;
CREATE SCHEMA IF NOT EXISTS consent;
CREATE SCHEMA IF NOT EXISTS delegation;

-- Grant permissions
GRANT ALL PRIVILEGES ON SCHEMA keycloak TO admin;
GRANT ALL PRIVILEGES ON SCHEMA travel TO admin;
GRANT ALL PRIVILEGES ON SCHEMA expense TO admin;
GRANT ALL PRIVILEGES ON SCHEMA approval TO admin;
GRANT ALL PRIVILEGES ON SCHEMA consent TO admin;
GRANT ALL PRIVILEGES ON SCHEMA delegation TO admin;
